name: loopify
version: 1.0.0+1
description: A Flutter version of the Tune Cloud Play app
environment:
  sdk: '>=3.8.0 <4.0.0'
publish_to: 'none'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_selector: ^1.0.3
  just_audio: ^0.9.36
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  provider: ^6.0.0
  palette_generator: ^0.3.3
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.10
  blur: ^3.1.0
  share_plus: ^7.2.1
  audio_service: ^0.18.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
